return T{
    ["4"] = {
        ActionType              = 'Command',
        Macro                   = T{
            "/mdt",
        },
        Label                   = "MDT",
        Image                   = "spells/143.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = true,
    },
    ["8"] = {
        ActionType              = 'Command',
        Macro                   = T{
            "/wires",
        },
        Label                   = "Wind",
        Image                   = "spells/154.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = true,
    },
    ["1"] = {
        ActionType              = 'Command',
        Macro                   = T{
            "/fres",
        },
        Label                   = "Fire",
        Image                   = "spells/144.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = true,
    },
    ["5"] = {
        ActionType              = 'Command',
        Macro                   = T{
            "/kite",
        },
        Label                   = "Kite",
        Image                   = "spells/521.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = true,
    },
    ["9"] = {
        ActionType              = 'Command',
        Macro                   = T{
            "/wares",
        },
        Label                   = "Water",
        Image                   = "spells/169.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = true,
    },
    ["6"] = {
        ActionType              = 'Command',
        Macro                   = T{
            "/ires",
        },
        Label                   = "Ice",
        Image                   = "spells/149.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = true,
    },
    ["3"] = {
        ActionType              = 'Command',
        Macro                   = T{
            "/pdt",
        },
        Label                   = "PDT",
        Image                   = "spells/910.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = true,
    },
    ["7"] = {
        ActionType              = 'Command',
        Macro                   = T{
            "/eres",
        },
        Label                   = "Earth",
        Image                   = "spells/159.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = true,
    },
    ["2"] = {
        ActionType              = 'Command',
        Macro                   = T{
            "/tres",
        },
        Label                   = "Lightning",
        Image                   = "spells/164.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = true,
    },
};